# -*- coding: utf-8 -*-
"""Learning OpenCV4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rXQki-laiugjoEU9knDvLUawodYcoz8y
"""
import numpy as np
import scipy
import cv2

img = np.zeros((3, 3), dtype=np.uint8)
print(img)

img = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)

img = np.zeros((5, 3), dtype=np.uint8)
print(img.shape)

image = cv2.imread('/content/lady.jpg')
cv2.imwrite('/content/lady.png', image)

grayImage = cv2.imread('/content/lady.png', cv2.IMREAD_GRAYSCALE)
cv2.imwrite('/content/ladyGray.png', grayImage)


cv2.imshow(grayImage)

import os

#Make an array of 120,000 random bytes
randomByteArray = bytearray(os.urandom(120000))
flatNumpyArray = np.array(randomByteArray)

#Convert the array to make a 400x300 grayscale image
grayImage = flatNumpyArray.reshape(300, 400)
cv2.imwrite('RandomGray.png', grayImage)

cv2.imshow(grayImage)

#Convert the array to make a 400x100 color image
bgrImage = flatNumpyArray.reshape(100, 400, 3)
cv2.imwrite('RandomColor.png', bgrImage)

cv2.imshow(bgrImage)

"""Acessing image data with numpy.array

"""

import cv2

img = cv2.imread('/content/lady.png')
img[0, 0] = [255, 255, 255]
cv2.imshow(img)

img = cv2.imread('/content/lady.png')
img.itemset((150, 120, 0), 255)
print(img.item(150, 120, 0))

img = cv2.imread('/content/lady.png')
img[:, :, 1] = 0

cv2.imshow(img)

"""REGIONS OF INTERESTS"""

img = cv2.imread('/content/lady.png')
my_roi = img[0:100, 0:100]
img[300:400, 300:400] = my_roi
cv2.imshow(img)

img = cv2.imread('/content/lady.png')
print(img.shape)
print(img.size)
print(img.dtype)

"""Reading/Writing a Video File"""

videoCapture = cv2.VideoCapture('/content/kitten.mp4')
fps = videoCapture.get(cv2.CAP_PROP_FPS)
size = (int(videoCapture.get(cv2.CAP_PROP_FRAME_WIDTH)),
        int(videoCapture.get(cv2.CAP_PROP_FRAME_HEIGHT)))
videoWriter = cv2.VideoWriter('/content/kitten.mp4', cv2.VideoWriter_fourcc('M', 'P', '4', 'V'),
                              fps, size)
success, frame = videoCapture.read()
while success: #Loop until the are no more frames.
    videoWriter.write(frame)
    success, frame = videoCapture.read()

"""Capturing Camera Frames"""

cameraCapture = cv2.VideoCapture(0)
fps = 30 #An assumption
size = (int(cameraCapture.get(cv2.CAP_PROP_FRAME_WIDTH)),
        int(cameraCapture.get(cv2.CAP_PROP_FRAME_HEIGHT)))
videoWriter = cv2.VideoWriter(
    '/content/kitten.mp4', cv2.VideoWriter_fourcc('M', 'P', '4', 'V'),
    fps, size)

success, frame = cameraCapture.read()
numFramesRemaining = 10 * fps - 1 #10 seconds of frame
while success and numFramesRemaining > 0:
    videoWriter.write(frame)
    success, frame = cameraCapture.read()
    numFramesRemaining -= 1

"""Displaying an Image in a Window"""

img = cv2.imread('/content/lady.png')
cv2.imshow(img)
cv2.waitKey()
cv2.destroyAllWindows()